[[expense_tracker.owners]]
name = "Owner 1"
color = "#da70d6"

[[expense_tracker.owners]]
name = "Owner 2"
color = "#00bfff"

[expense_tracker.transaction_tab.defaults]
shared = true

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1QGq30uszyxQzAoARVy4pZE0LElwIuXXMbFc5g4ftjVk/edit?usp=sharing"
worksheet = 0
